# Generated by Django 4.2.1 on 2023-05-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solidPayApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='channel',
            field=models.CharField(default='', max_length=300),
        ),
    ]
