# Generated by Django 4.2.1 on 2023-05-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solidPayApp', '0002_paymentrequest_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='USDPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privateKey', models.CharField(max_length=1000)),
                ('createdAddress', models.CharField(max_length=500)),
                ('pendingAmountUSD', models.DecimalField(decimal_places=10, max_digits=30)),
                ('pendingAmountETH', models.DecimalField(decimal_places=10, max_digits=30)),
                ('ETHprice', models.DecimalField(decimal_places=10, max_digits=10)),
                ('destinationAddress', models.CharField(max_length=500)),
                ('channel', models.CharField(default='', max_length=300)),
                ('fullfilled', models.BooleanField(default=False)),
                ('requestDate', models.DateTimeField()),
            ],
        ),
    ]
