# Generated by Django 4.2.1 on 2023-06-04 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solidPayApp', '0004_nonemptywallets_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonemptywallets',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 20, 0, 34, 540798)),
        ),
    ]
