# Generated by Django 4.2.1 on 2023-09-03 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solidPayApp', '0005_nonemptywallets_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonemptywallets',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 3, 20, 47, 49, 288310)),
        ),
    ]
